CREATE OR REPLACE TRIGGER trg_review_one_per_product
BEFORE INSERT ON Review
FOR EACH ROW
DECLARE
    v_cnt   NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_cnt                       
    FROM Review
    WHERE user_id = :NEW.user_id
      AND product_id = :NEW.product_id;

    IF v_cnt > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            '같은 제품에 대해서는 리뷰를 한 번만 작성할 수 있습니다.'
        );
    END IF;

    IF :NEW.created_at IS NULL THEN
        :NEW.created_at := SYSDATE;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BRAND_ID
BEFORE INSERT ON Brand
FOR EACH ROW
WHEN (NEW.brand_id IS NULL)
BEGIN
    :NEW.brand_id := SEQ_BRAND_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CATEGORY_ID
BEFORE INSERT ON ProductCategory
FOR EACH ROW
WHEN (NEW.category_id IS NULL)
BEGIN
    :NEW.category_id := SEQ_CATEGORY_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCT_ID
BEFORE INSERT ON Product
FOR EACH ROW
WHEN (NEW.product_id IS NULL)
BEGIN
    :NEW.product_id := SEQ_PRODUCT_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_INGREDIENT_ID
BEFORE INSERT ON Ingredient
FOR EACH ROW
WHEN (NEW.ingr_id IS NULL)
BEGIN
    :NEW.ingr_id := SEQ_INGREDIENT_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEW_ID
BEFORE INSERT ON Review
FOR EACH ROW
WHEN (NEW.review_id IS NULL)
BEGIN
    :NEW.review_id := SEQ_REVIEW_ID.NEXTVAL;
END;
/