ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

DROP USER ynna CASCADE;

CREATE USER ynna IDENTIFIED BY "0000"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO ynna;
GRANT CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW TO ynna;

COMMIT;

TRUNCATE TABLE ProductCategory;
DROP SEQUENCE SEQ_CATEGORY_ID;

DROP TABLE Product CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PRODUCT_ID;

DROP TABLE Ingredient CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INGREDIENT_ID;

DROP TABLE RiskIngredient CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_RISKINGREDIENT_ID;

DROP TABLE AllergyIngredient CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_ALLERGYINGREDIENT_ID;

TRUNCATE TABLE ProductIngredient_REL;
TRUNCATE TABLE Product;
DROP SEQUENCE SEQ_PRODUCT_ID;

COMMIT;

SELECT COUNT(*) AS row_count
FROM PRODUCTINGREDIENT_REL;