DROP VIEW UserProfile;


DROP TABLE ReviewTag_REL CASCADE CONSTRAINTS PURGE;
DROP TABLE Favorite CASCADE CONSTRAINTS PURGE;
DROP TABLE FollowUser CASCADE CONSTRAINTS PURGE;
DROP TABLE UserPreference CASCADE CONSTRAINTS PURGE;
DROP TABLE RecommendationLog CASCADE CONSTRAINTS PURGE;
DROP TABLE Review CASCADE CONSTRAINTS PURGE;
DROP TABLE ProductIngredient_REL CASCADE CONSTRAINTS PURGE;
DROP TABLE UserSkinType_REL CASCADE CONSTRAINTS PURGE;


DROP TABLE ReviewTag CASCADE CONSTRAINTS PURGE;
DROP TABLE RiskIngredient CASCADE CONSTRAINTS PURGE;
DROP TABLE AllergyIngredient CASCADE CONSTRAINTS PURGE;
DROP TABLE Ingredient CASCADE CONSTRAINTS PURGE;
DROP TABLE Product CASCADE CONSTRAINTS PURGE;
DROP TABLE ProductCategory CASCADE CONSTRAINTS PURGE;
DROP TABLE Brand CASCADE CONSTRAINTS PURGE;
DROP TABLE UserProfile_BASE CASCADE CONSTRAINTS PURGE;
DROP TABLE Users CASCADE CONSTRAINTS PURGE;


DROP SEQUENCE SEQ_REC_ID;
DROP SEQUENCE SEQ_REVIEW_ID;
DROP SEQUENCE SEQ_INGREDIENT_ID;
DROP SEQUENCE SEQ_PRODUCT_ID;
DROP SEQUENCE SEQ_CATEGORY_ID;
DROP SEQUENCE SEQ_BRAND_ID;
